#!/usr/bin/env bash
# Deploy the backend stack to the EC2 host provisioned by terraform/.
# Usage: ./deploy.sh [--seed] [--skip-migrate]
#
# Migrations run by default, before the new code serves. --skip-migrate is an
# escape hatch for a code-only rollback, not a normal path.
# First run generates server-side secrets in /home/ec2-user/pod-v2/.env
# (secrets live on the server only, never in the repo).
set -euo pipefail

cd "$(dirname "$0")"

HOST="${HOST:-$(terraform -chdir=terraform output -raw backend_public_ip)}"
DOMAIN="${DOMAIN:-${HOST}.sslip.io}"
S3_BUCKET="${S3_BUCKET:-$(terraform -chdir=terraform output -raw evidence_bucket)}"
SSH="ssh -o StrictHostKeyChecking=accept-new ec2-user@${HOST}"
AWS_REGION="${AWS_REGION:-ap-southeast-1}"
SECRET_NAME="${SECRET_NAME:-$(terraform -chdir=terraform output -raw runtime_secret_name)}"
REMOTE_DIR=/home/ec2-user/pod-v2

# The one cutover point for the database. Left unset, every URL rendered below
# names the co-located Postgres container by its compose service name, which is
# byte for byte what every deploy before Aurora produced. Set it to the Aurora
# writer endpoint and the runtime URL and the migration URL move together: they
# must never disagree, or migrations land in one database while reads come from
# another, and the schema drift is only visible at 500-time.
#
# Reverting is unsetting this and redeploying. Nothing else is pinned to it.
DB_HOST="${DB_HOST:-postgres}"

echo "==> Deploying to ${HOST} (https://${DOMAIN})"

# A cutover nobody can see is a cutover somebody debugs against the wrong
# database for an afternoon. Name the target out loud, on every deploy, before
# a single byte moves.
if [[ "${DB_HOST}" == "postgres" ]]; then
  echo "==> Database: co-located Postgres container (compose service 'postgres')"
else
  echo "==> Database: ${DB_HOST}"
  echo "               ^ NOT the co-located container. To revert: unset DB_HOST, redeploy."
fi

echo "==> Syncing sources"
rsync -az --delete \
  --exclude node_modules --exclude dist --exclude .env \
  ../backend "ec2-user@${HOST}:${REMOTE_DIR}/"
# systemd/ is shipped but not installed: writing to /etc needs root and a
# daemon-reload, which is a deliberate one-time step, not something a routine
# deploy should do behind your back. See AURORA.md for the install line.
rsync -az docker-compose.prod.yml Caddyfile init-db systemd "ec2-user@${HOST}:${REMOTE_DIR}/"
echo "==> Rendering .env from Secrets Manager"
# Secrets are generated by Terraform and stored in Secrets Manager. The
# instance reads them with its own IAM role at deploy time, so nothing
# sensitive is committed, typed on a command line, or left in shell history.
# The rendered file is root-readable only and holds no value that cannot be
# rotated by updating the secret and redeploying.
$SSH "cd ${REMOTE_DIR} && aws secretsmanager get-secret-value \
  --secret-id '${SECRET_NAME}' --region '${AWS_REGION}' --query SecretString --output text \
  > /tmp/pod-secrets.json && python3 - <<'PYEOF'
import json, pathlib, shutil
secrets = json.load(open('/tmp/pod-secrets.json'))
env = {
    'NODE_ENV': 'production',
    'PORT': '3000',
    'DOMAIN': '${DOMAIN}',
    'POSTGRES_USER': 'pod',
    'POSTGRES_DB': 'pod',
    'POSTGRES_PASSWORD': secrets['POSTGRES_PASSWORD'],
    'POD_APP_PASSWORD': secrets['POD_APP_PASSWORD'],
    'JWT_SECRET': secrets['JWT_SECRET'],
    'DATABASE_URL': f\"postgres://pod_app:{secrets['POD_APP_PASSWORD']}@${DB_HOST}:5432/pod\",
    'DATABASE_OWNER_URL': f\"postgres://pod:{secrets['POSTGRES_PASSWORD']}@${DB_HOST}:5432/pod\",
    'AWS_REGION': '${AWS_REGION}',
    'S3_BUCKET': '${S3_BUCKET}',
    'BEDROCK_MODEL_ID': 'global.anthropic.claude-haiku-4-5-20251001-v1:0',
    'AI_ENABLED': 'true',
    'DUAL_WRITE_PODS': 'true',
    'MIN_APP_VERSION': '1.0.0',
    'LATEST_APP_VERSION': '2.0.0',
    'BLOCKED_APP_VERSIONS': '',
}
env_path = pathlib.Path('.env')
# Keep the render this one replaces. After a cutover, .env.prev holds the
# literal pre-Aurora connection strings, so a revert is verified by diffing two
# files on the box instead of by trusting someone's memory of a hostname.
# copy2 carries the 0600 mode over, so the copy is no more readable than the
# original.
if env_path.exists():
    shutil.copy2(env_path, '.env.prev')
env_path.write_text('\\n'.join(f'{k}={v}' for k, v in env.items()) + '\\n')
PYEOF
chmod 600 .env && rm -f /tmp/pod-secrets.json"

# From here until the health check passes, .env on the box names a database that
# nothing has yet proved works. That file outlives this script: the containers
# carry `restart: unless-stopped`, so the next crash or reboot recreates them
# against whatever .env says, with no deploy in anyone's shell history to blame.
# The demo-roll timer reads DATABASE_OWNER_URL out of the same file, so a failed
# cutover would also redirect the nightly roll away from the database still
# serving traffic.
#
# A deferred promote does not fit: compose has to read .env to start the
# containers this deploy is testing. So the write stays where it is and the
# failure path is what gets fixed. Any non-zero exit below puts the previous
# .env back, which leaves the box pointing at the database it was already on.
ENV_ROLLBACK_ARMED=1
restore_env_on_failure() {
  status=$?
  if [ "$status" -ne 0 ] && [ "$ENV_ROLLBACK_ARMED" -eq 1 ]; then
    echo "==> Deploy failed (exit ${status}). Restoring the previous .env so a later restart"
    echo "    does not silently come up against an unproven database."
    $SSH "cd ${REMOTE_DIR} && if [ -f .env.prev ]; then cp -p .env.prev .env && \
      echo '    .env restored to:' && sed -n 's|^DATABASE_URL=postgres://[^@]*@\([^:]*\):.*|      \1|p' .env; \
      else echo '    no .env.prev existed, nothing to restore'; fi" || true
  fi
}
trap restore_env_on_failure EXIT

echo "==> Building image"
$SSH "cd ${REMOTE_DIR} && docker build -t pod-backend:latest backend/"

# Migrations run BY DEFAULT, and BEFORE the new code serves a single request.
#
# They used to be opt-in behind --migrate, and to run after `compose up`. Both
# were wrong in the same way: a deploy that forgot the flag, or that raced it,
# put code in front of traffic that queried columns the database did not have
# yet. That is not a subtle failure - it is a 500 on the first request, and it
# happened here on the deploy that added drivers.email.
#
# Running first is safe because the migrations are expand-only by policy: they
# add, never rename or drop, so the OLD code keeps working against the NEW
# schema for the seconds between these two steps. Contract steps are a separate,
# deliberate release. Applied migrations are tracked, so this is a no-op when
# nothing is pending.
if [[ "${*:-}" == *--skip-migrate* ]]; then
  echo "==> SKIPPING migrations (--skip-migrate)"
else
  echo "==> Running migrations (as owner role, before the new code serves)"
  $SSH "cd ${REMOTE_DIR} && docker compose -f docker-compose.prod.yml --env-file .env run --rm \
    -e DATABASE_URL=\$(grep '^DATABASE_OWNER_URL=' .env | cut -d= -f2-) \
    backend-1 node dist/database/migrate.js"
fi

echo "==> Starting stack"
$SSH "cd ${REMOTE_DIR} && docker compose -f docker-compose.prod.yml --env-file .env up -d --remove-orphans"

# The Caddyfile is bind-mounted as a single FILE, and rsync ships a new file
# then renames it into place. The rename gives it a fresh inode, and a bind
# mount resolves its inode when the container is created - so the running
# Caddy goes on serving the config it started with, and `compose up` sees no
# reason to recreate it. Every Caddyfile change would silently not apply.
#
# Validating in a throwaway container first is what makes this safe: it mounts
# the file that is actually on disk now, so a syntax error fails the deploy
# here, with the site still up, rather than putting Caddy into a crash loop
# where nothing is served at all. `set -e` does the aborting.
echo "==> Validating Caddyfile"
$SSH "cd ${REMOTE_DIR} && docker run --rm -e DOMAIN='${DOMAIN}' \
  -v \"\$PWD/Caddyfile:/etc/caddy/Caddyfile:ro\" caddy:2-alpine \
  caddy validate --config /etc/caddy/Caddyfile 2>&1 | tail -1"

echo "==> Reloading Caddy onto the new config"
# caddy_data is a named volume and is untouched, so issued TLS certificates
# survive and nothing is re-requested from Let's Encrypt.
$SSH "cd ${REMOTE_DIR} && docker compose -f docker-compose.prod.yml --env-file .env \
  up -d --force-recreate caddy"

if [[ "${*:-}" == *--seed* ]]; then
  echo "==> Seeding (as owner role)"
  $SSH "cd ${REMOTE_DIR} && docker compose -f docker-compose.prod.yml --env-file .env run --rm \
    -e DATABASE_URL=\$(grep '^DATABASE_OWNER_URL=' .env | cut -d= -f2-) \
    backend-1 node dist/database/seeds/seed.js"
fi

echo "==> Health"
sleep 5
curl -fsS "https://${DOMAIN}/api/health" && echo
# The privacy policy is what the Google Play listing points at, and Play
# re-checks it after launch, so a deploy that leaves it unreachable is a
# store-listing problem. Cheap to assert here; expensive to discover later.
curl -fsS -o /dev/null "https://${DOMAIN}/privacy" && echo "privacy policy: ok"

# The database this deploy names has now answered a real request, so .env is
# worth keeping. Disarm the restore before it can undo a good deploy.
ENV_ROLLBACK_ARMED=0

# Whenever the database changes underneath the app, the demo round has to be
# rolled on the new one before anyone looks at it.
#
# The roll shifts stops whose created_at is before today, and the app selects a
# round the same way. A database that has not been rolled today therefore serves
# an empty round to every driver login, which is indistinguishable from a broken
# deploy. Two ways in: a cutover to a cluster loaded from a dump taken yesterday,
# and a cutover that happens after 00:05 UTC, where Persistent=true will not
# re-fire a timer that already ran against the other database.
#
# Running it here is safe on any database and on any deploy: the SQL only shifts
# timestamps forward and deletes nothing, and a round already rolled today
# matches no rows.
if [[ "${DB_HOST}" != "postgres" ]]; then
  echo "==> Rolling the demo round on ${DB_HOST}"
  $SSH "sudo systemctl start pod-demo-roll.service && \
        systemctl show pod-demo-roll.service -p Result --value | sed 's/^/    roll result: /'" || \
    echo "    roll did not run. Check: sudo systemctl status pod-demo-roll.service"
fi

echo "==> Done: https://${DOMAIN}"
