#!/usr/bin/env bash
# Deploy the backend stack to the EC2 host provisioned by terraform/.
# Usage: ./deploy.sh [--seed] [--migrate]
# First run generates server-side secrets in /home/ec2-user/pod-v2/.env
# (secrets live on the server only, never in the repo).
set -euo pipefail

cd "$(dirname "$0")"

HOST="${HOST:-$(terraform -chdir=terraform output -raw backend_public_ip)}"
DOMAIN="${DOMAIN:-${HOST}.sslip.io}"
S3_BUCKET="${S3_BUCKET:-$(terraform -chdir=terraform output -raw evidence_bucket)}"
SSH="ssh -o StrictHostKeyChecking=accept-new ec2-user@${HOST}"
AWS_REGION="${AWS_REGION:-ap-southeast-1}"
SECRET_NAME="${SECRET_NAME:-$(terraform -chdir=terraform output -raw runtime_secret_name)}"
REMOTE_DIR=/home/ec2-user/pod-v2

echo "==> Deploying to ${HOST} (https://${DOMAIN})"

echo "==> Syncing sources"
rsync -az --delete \
  --exclude node_modules --exclude dist --exclude .env \
  ../backend "ec2-user@${HOST}:${REMOTE_DIR}/"
rsync -az docker-compose.prod.yml Caddyfile init-db "ec2-user@${HOST}:${REMOTE_DIR}/"
$SSH "mkdir -p ${REMOTE_DIR}/dashboard-dist"
if [ -d ../dashboard/dist ]; then
  rsync -az --delete ../dashboard/dist/ "ec2-user@${HOST}:${REMOTE_DIR}/dashboard-dist/"
fi

echo "==> Rendering .env from Secrets Manager"
# Secrets are generated by Terraform and stored in Secrets Manager. The
# instance reads them with its own IAM role at deploy time, so nothing
# sensitive is committed, typed on a command line, or left in shell history.
# The rendered file is root-readable only and holds no value that cannot be
# rotated by updating the secret and redeploying.
$SSH "cd ${REMOTE_DIR} && aws secretsmanager get-secret-value \
  --secret-id '${SECRET_NAME}' --region '${AWS_REGION}' --query SecretString --output text \
  > /tmp/pod-secrets.json && python3 - <<'PYEOF'
import json, pathlib
secrets = json.load(open('/tmp/pod-secrets.json'))
env = {
    'NODE_ENV': 'production',
    'PORT': '3000',
    'DOMAIN': '${DOMAIN}',
    'POSTGRES_USER': 'pod',
    'POSTGRES_DB': 'pod',
    'POSTGRES_PASSWORD': secrets['POSTGRES_PASSWORD'],
    'POD_APP_PASSWORD': secrets['POD_APP_PASSWORD'],
    'JWT_SECRET': secrets['JWT_SECRET'],
    'DATABASE_URL': f\"postgres://pod_app:{secrets['POD_APP_PASSWORD']}@postgres:5432/pod\",
    'DATABASE_OWNER_URL': f\"postgres://pod:{secrets['POSTGRES_PASSWORD']}@postgres:5432/pod\",
    'AWS_REGION': '${AWS_REGION}',
    'S3_BUCKET': '${S3_BUCKET}',
    'BEDROCK_MODEL_ID': 'global.anthropic.claude-haiku-4-5-20251001-v1:0',
    'AI_ENABLED': 'true',
    'DUAL_WRITE_PODS': 'true',
    'MIN_APP_VERSION': '1.0.0',
    'LATEST_APP_VERSION': '2.0.0',
    'BLOCKED_APP_VERSIONS': '',
}
pathlib.Path('.env').write_text('\\n'.join(f'{k}={v}' for k, v in env.items()) + '\\n')
PYEOF
chmod 600 .env && rm -f /tmp/pod-secrets.json"

echo "==> Building image and starting stack"
$SSH "cd ${REMOTE_DIR} && docker build -t pod-backend:latest backend/ \
  && docker compose -f docker-compose.prod.yml --env-file .env up -d --remove-orphans"

if [[ "${*:-}" == *--migrate* ]]; then
  echo "==> Running migrations (as owner role)"
  $SSH "cd ${REMOTE_DIR} && docker compose -f docker-compose.prod.yml --env-file .env run --rm \
    -e DATABASE_URL=\$(grep '^DATABASE_OWNER_URL=' .env | cut -d= -f2-) \
    backend-1 node dist/database/migrate.js"
fi

if [[ "${*:-}" == *--seed* ]]; then
  echo "==> Seeding (as owner role)"
  $SSH "cd ${REMOTE_DIR} && docker compose -f docker-compose.prod.yml --env-file .env run --rm \
    -e DATABASE_URL=\$(grep '^DATABASE_OWNER_URL=' .env | cut -d= -f2-) \
    backend-1 node dist/database/seeds/seed.js"
fi

echo "==> Health"
sleep 3
curl -fsS "https://${DOMAIN}/api/health" && echo
echo "==> Done: https://${DOMAIN}"
