#!/usr/bin/env bash
# Deploy the backend stack to the EC2 host provisioned by terraform/.
# Usage: ./deploy.sh [--seed] [--migrate]
# First run generates server-side secrets in /home/ec2-user/pod-v2/.env
# (secrets live on the server only, never in the repo).
set -euo pipefail

cd "$(dirname "$0")"

HOST="${HOST:-$(terraform -chdir=terraform output -raw backend_public_ip)}"
DOMAIN="${DOMAIN:-${HOST}.sslip.io}"
S3_BUCKET="${S3_BUCKET:-$(terraform -chdir=terraform output -raw evidence_bucket)}"
SSH="ssh -o StrictHostKeyChecking=accept-new ec2-user@${HOST}"
AWS_REGION="${AWS_REGION:-ap-southeast-1}"
SECRET_NAME="${SECRET_NAME:-$(terraform -chdir=terraform output -raw runtime_secret_name)}"
REMOTE_DIR=/home/ec2-user/pod-v2

echo "==> Deploying to ${HOST} (https://${DOMAIN})"

echo "==> Syncing sources"
rsync -az --delete \
  --exclude node_modules --exclude dist --exclude .env \
  ../backend "ec2-user@${HOST}:${REMOTE_DIR}/"
rsync -az docker-compose.prod.yml Caddyfile init-db "ec2-user@${HOST}:${REMOTE_DIR}/"
echo "==> Rendering .env from Secrets Manager"
# Secrets are generated by Terraform and stored in Secrets Manager. The
# instance reads them with its own IAM role at deploy time, so nothing
# sensitive is committed, typed on a command line, or left in shell history.
# The rendered file is root-readable only and holds no value that cannot be
# rotated by updating the secret and redeploying.
$SSH "cd ${REMOTE_DIR} && aws secretsmanager get-secret-value \
  --secret-id '${SECRET_NAME}' --region '${AWS_REGION}' --query SecretString --output text \
  > /tmp/pod-secrets.json && python3 - <<'PYEOF'
import json, pathlib
secrets = json.load(open('/tmp/pod-secrets.json'))
env = {
    'NODE_ENV': 'production',
    'PORT': '3000',
    'DOMAIN': '${DOMAIN}',
    'POSTGRES_USER': 'pod',
    'POSTGRES_DB': 'pod',
    'POSTGRES_PASSWORD': secrets['POSTGRES_PASSWORD'],
    'POD_APP_PASSWORD': secrets['POD_APP_PASSWORD'],
    'JWT_SECRET': secrets['JWT_SECRET'],
    'DATABASE_URL': f\"postgres://pod_app:{secrets['POD_APP_PASSWORD']}@postgres:5432/pod\",
    'DATABASE_OWNER_URL': f\"postgres://pod:{secrets['POSTGRES_PASSWORD']}@postgres:5432/pod\",
    'AWS_REGION': '${AWS_REGION}',
    'S3_BUCKET': '${S3_BUCKET}',
    'BEDROCK_MODEL_ID': 'global.anthropic.claude-haiku-4-5-20251001-v1:0',
    'AI_ENABLED': 'true',
    'DUAL_WRITE_PODS': 'true',
    'MIN_APP_VERSION': '1.0.0',
    'LATEST_APP_VERSION': '2.0.0',
    'BLOCKED_APP_VERSIONS': '',
}
pathlib.Path('.env').write_text('\\n'.join(f'{k}={v}' for k, v in env.items()) + '\\n')
PYEOF
chmod 600 .env && rm -f /tmp/pod-secrets.json"

echo "==> Building image and starting stack"
$SSH "cd ${REMOTE_DIR} && docker build -t pod-backend:latest backend/ \
  && docker compose -f docker-compose.prod.yml --env-file .env up -d --remove-orphans"

# The Caddyfile is bind-mounted as a single FILE, and rsync ships a new file
# then renames it into place. The rename gives it a fresh inode, and a bind
# mount resolves its inode when the container is created - so the running
# Caddy goes on serving the config it started with, and `compose up` sees no
# reason to recreate it. Every Caddyfile change would silently not apply.
#
# Validating in a throwaway container first is what makes this safe: it mounts
# the file that is actually on disk now, so a syntax error fails the deploy
# here, with the site still up, rather than putting Caddy into a crash loop
# where nothing is served at all. `set -e` does the aborting.
echo "==> Validating Caddyfile"
$SSH "cd ${REMOTE_DIR} && docker run --rm -e DOMAIN='${DOMAIN}' \
  -v \"\$PWD/Caddyfile:/etc/caddy/Caddyfile:ro\" caddy:2-alpine \
  caddy validate --config /etc/caddy/Caddyfile 2>&1 | tail -1"

echo "==> Reloading Caddy onto the new config"
# caddy_data is a named volume and is untouched, so issued TLS certificates
# survive and nothing is re-requested from Let's Encrypt.
$SSH "cd ${REMOTE_DIR} && docker compose -f docker-compose.prod.yml --env-file .env \
  up -d --force-recreate caddy"

if [[ "${*:-}" == *--migrate* ]]; then
  echo "==> Running migrations (as owner role)"
  $SSH "cd ${REMOTE_DIR} && docker compose -f docker-compose.prod.yml --env-file .env run --rm \
    -e DATABASE_URL=\$(grep '^DATABASE_OWNER_URL=' .env | cut -d= -f2-) \
    backend-1 node dist/database/migrate.js"
fi

if [[ "${*:-}" == *--seed* ]]; then
  echo "==> Seeding (as owner role)"
  $SSH "cd ${REMOTE_DIR} && docker compose -f docker-compose.prod.yml --env-file .env run --rm \
    -e DATABASE_URL=\$(grep '^DATABASE_OWNER_URL=' .env | cut -d= -f2-) \
    backend-1 node dist/database/seeds/seed.js"
fi

echo "==> Health"
sleep 5
curl -fsS "https://${DOMAIN}/api/health" && echo
# The privacy policy is what the Google Play listing points at, and Play
# re-checks it after launch, so a deploy that leaves it unreachable is a
# store-listing problem. Cheap to assert here; expensive to discover later.
curl -fsS -o /dev/null "https://${DOMAIN}/privacy" && echo "privacy policy: ok"
echo "==> Done: https://${DOMAIN}"
