variable "name" {
  type    = string
  default = "pod-v2/runtime"
}

# Generated by Terraform, never by a human and never committed. The values
# live in Secrets Manager and in Terraform state (which is why state is
# itself sensitive). Nothing is baked into an image, and no secret is stored
# in git or passed on a command line.
resource "random_password" "postgres" {
  length  = 40
  special = false
}

resource "random_password" "pod_app" {
  length  = 40
  special = false
}

resource "random_password" "jwt" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "runtime" {
  name                    = var.name
  description             = "Runtime secrets for the PoD v2 API"
  recovery_window_in_days = 0 # take-home: allow immediate re-create on destroy
}

resource "aws_secretsmanager_secret_version" "runtime" {
  secret_id = aws_secretsmanager_secret.runtime.id

  secret_string = jsonencode({
    POSTGRES_PASSWORD = random_password.postgres.result
    POD_APP_PASSWORD  = random_password.pod_app.result
    JWT_SECRET        = random_password.jwt.result
  })

  # Rotation happens through Secrets Manager, not by Terraform overwriting a
  # live value on every apply: an unplanned rewrite here would lock the API
  # out of its own database.
  lifecycle {
    ignore_changes = [secret_string]
  }
}

output "secret_arn" { value = aws_secretsmanager_secret.runtime.arn }
output "secret_name" { value = aws_secretsmanager_secret.runtime.name }
